CREATE TABLE [dbo].[Throws]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY , 
    [DateCreated] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [Result] VARCHAR(10) NULL, 
    [ExperimentId] UNIQUEIDENTIFIER NULL, 
    [VideoUrl] VARCHAR(MAX) NULL, 
    [ImageUrl] VARCHAR(MAX) NULL, 
    [ResultProcessedDate] DATETIME NULL, 
	[ThrowNumber] INT IDENTITY(10000000,1) NOT NULL, 
    [Version] TINYINT NULL DEFAULT 2
)
